### ISSUE TITLE
how to solve this jepsen test error in tendermint? main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why: com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1

### ISSUE THREAD

**Issue by abi1296** [jepsen-io/tendermint#2]
I am running the code from this repository https://github.com/jepsen-io/tendermint without changing any files. But i am getting error while running the command lein run test.

The error that I got is mentioned below.
Initializing core.typed ...
Building core.typed base environments ...
Finished building base environments
"Elapsed time: 3347.461907 msecs"
core.typed initialized.
241:  Not checking jepsen.tendermint.validator/byzantine-validators definition
WARNING:  (jepsen/tendermint/validator.clj:662:5)  Local became bottom when checking case default
WARNING:  (jepsen/tendermint/validator.clj:678:5)  Local became bottom when checking case default
792:  Not checking jepsen.tendermint.validator/rand-legal-transition definition
15:33:32.220 [main] INFO  jepsen.cli - Test options:
 {:concurrency 5,
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil},
 :nemesis :none,
 :abci-url
 "https://s3-us-west-2.amazonaws.com/tendermint/binaries/abci/v0.5.0/abci_0.5.0_linux_amd64.zip",
 :nodes ["n1" "n2" "n3" "n4" "n5"],
 :test-count 1,
 :merkleeyes-url
 "https://s3-us-west-2.amazonaws.com/tendermint/jepsen/merkleeyes_0.2.2-ngc.3_linux_amd64.zip",
 :tendermint-url
 "https://s3-us-west-2.amazonaws.com/tendermint/binaries/tendermint/v0.10.3/tendermint_0.10.3_linux_amd64.zip",
 :time-limit 60,
 :workload :cas-register}

INFO [2019-10-14 15:33:32,273] jepsen test runner - jepsen.core Running test:
 {:concurrency 5,
 :nonserializable-keys [:validator-config],
 :db
 #object[jepsen.tendermint.db$db$reify__31900 0x2a8b1e67 "jepsen.tendermint.db$db$reify__31900@2a8b1e67"],
 :name "tendermint cas-register none",
 :start-time
 #object[org.joda.time.DateTime 0x731d35b0 "2019-10-14T15:33:32.000+05:30"],
 :net
 #object[jepsen.net$reify__1090 0x3a9c5f14 "jepsen.net$reify__1090@3a9c5f14"],
 :client
 #object[jepsen.tendermint.core$cas_register_client$reify__31918 0x362e1181 "jepsen.tendermint.core$cas_register_client$reify__31918@362e1181"],
 :barrier
 #object[java.util.concurrent.CyclicBarrier 0x2461a62c "java.util.concurrent.CyclicBarrier@2461a62c"],
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil},
 :checker
 #object[jepsen.checker$compose$reify__3207 0x1c63d92e "jepsen.checker$compose$reify__3207@1c63d92e"],
 :validator-config #<Atom@7a986079: nil>,
 :nemesis
 #object[jepsen.nemesis$reify__1123 0xb7a2b89 "jepsen.nemesis$reify__1123@b7a2b89"],
 :active-histories #<Atom@3e0e2a80: #{}>,
 :abci-url
 "https://s3-us-west-2.amazonaws.com/tendermint/binaries/abci/v0.5.0/abci_0.5.0_linux_amd64.zip",
 :nodes ["n1" "n2" "n3" "n4" "n5"],
 :test-count 1,
 :merkleeyes-url
 "https://s3-us-west-2.amazonaws.com/tendermint/jepsen/merkleeyes_0.2.2-ngc.3_linux_amd64.zip",
 :tendermint-url
 "https://s3-us-west-2.amazonaws.com/tendermint/binaries/tendermint/v0.10.3/tendermint_0.10.3_linux_amd64.zip",
 :generator
 #object[jepsen.generator$concat$reify__1922 0x17236e87 "jepsen.generator$concat$reify__1922@17236e87"],
 :os
 #object[jepsen.os.debian$reify__1367 0x75fa16cc "jepsen.os.debian$reify__1367@75fa16cc"],
 :time-limit 60,
 :workload :cas-register,
 :model {:value nil}}

ERROR [2019-10-14 15:33:32,385] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1
	at com.jcraft.jsch.Util.createSocket(Util.java:349) ~[jsch-0.1.53.jar:na]
	at com.jcraft.jsch.Session.connect(Session.java:215) ~[jsch-0.1.53.jar:na]
	at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.53.jar:na]
	at clj_ssh.ssh$fn__1395.invokeStatic(ssh.clj:118) ~[jepsen-0.1.6.jar:na]
	at clj_ssh.ssh$fn__1395.invoke(ssh.clj:115) ~[jepsen-0.1.6.jar:na]
	at clj_ssh.ssh.protocols$fn__1353$G__1320__1362.invoke(protocols.clj:4) ~[jepsen-0.1.6.jar:na]
	at clj_ssh.ssh$connect.invokeStatic(ssh.clj:401) ~[jepsen-0.1.6.jar:na]
	at clj_ssh.ssh$connect.invoke(ssh.clj:397) ~[jepsen-0.1.6.jar:na]
	at jepsen.control$clj_ssh_session.invokeStatic(control.clj:262) ~[jepsen-0.1.6.jar:na]
	at jepsen.control$clj_ssh_session.invoke(control.clj:254) ~[jepsen-0.1.6.jar:na]
	at jepsen.control$session$fn__1784.invoke(control.clj:276) ~[jepsen-0.1.6.jar:na]
	at jepsen.reconnect$open_BANG_$fn__1673.invoke(reconnect.clj:59) ~[jepsen-0.1.6.jar:na]
	at jepsen.reconnect$open_BANG_.invokeStatic(reconnect.clj:57) ~[jepsen-0.1.6.jar:na]
	at jepsen.reconnect$open_BANG_.invoke(reconnect.clj:54) ~[jepsen-0.1.6.jar:na]
	at jepsen.control$session.invokeStatic(control.clj:273) ~[jepsen-0.1.6.jar:na]
	at jepsen.control$session.invoke(control.clj:270) ~[jepsen-0.1.6.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:650) ~[clojure-1.8.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invoke(core.clj:641) ~[clojure-1.8.0.jar:na]
	at jepsen.util$fcatch$wrapper__945.doInvoke(util.clj:28) ~[jepsen-0.1.6.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
	at jepsen.util$real_pmap$launcher__950$fn__951.invoke(util.clj:48) ~[jepsen-0.1.6.jar:na]
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.8.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
Caused by: java.net.UnknownHostException: n1
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_222]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_222]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_222]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_222]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_222]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_222]
	at com.jcraft.jsch.Util.createSocket(Util.java:343) ~[jsch-0.1.53.jar:na]
	... 35 common frames omitted
Can anybody help me to solve this error? Thank you.

**Comment by Keerthana-Jayakumaran** [comment]
Hi,
Can you please tell, why the above error is comming?

**Comment by kaibimouez** [comment]
hi @abi1296 , 
please did you find a solution for this error : com.jcraft.jsch.JSchException: java.net.UnknownHostException: n1.

Thank you very much

**Comment by rachit77** [comment]
Hey @abi1296 did you find the solution for above error.
